### PR TITLE
Upgrade sdpa kernel

### PR DESCRIPTION
**Pull request by Ryu1845**
`torch.backends.cuda.sdp_kernel` is deprecated, this adds the replacement without changing the API (basically what PyTorch is currently doing internally). This mostly has the effect of removing the following warning.
```
FutureWarning: torch.backends.cuda.sdp_kernel() is deprecated. In the future, this context manager will be removed. Please see, torch.nn.attention.sdpa_kernel() for the new context manager, with updated signature.
```

### CODE REVIEW

**Comment by lucidrains** [comment]
@Ryu1845 nice! will this break for some versions of pytorch 2.x?

**Comment by Ryu1845** [comment]
Yes I think this is for >2.3, should I add a fallback, bump up the minimum PyTorch version, or do you think just keeping the deprecated kernel is better?

**Comment by AugustDev** [comment]
Could you please finalise with this, there's a lot of warnings about torch.backends.cuda.sdp_kernel() currently when using x-transformers?

**Comment by lucidrains** [comment]
@AugustDev @Ryu1845 hey Augustinas and Sofian

been procrastinating on this, but decided to make a move just now

could you let me know if it is fixed on the latest version?

**Pull request closed without merging**
