### PR TITLE
Fix bug with caching AliBi bias for differently shaped inputs

### PR DESCRIPTION
**Pull request by ilya16**
Hi! :)

The new AliBi code doesn't properly handle cached bias. If you pass both shorter and longer inputs, the model will crash due to a shape mismatch. This PR fixes these errors and also removes one redundant dimension for bias.

Code to reproduce the errors:

```python
import torch
from x_transformers import TransformerWrapper, Decoder

model = TransformerWrapper(
    num_tokens = 1000,
    max_seq_len = 1024,
    attn_layers = Decoder(
        dim = 512,
        depth = 3,
        alibi_pos_bias = True, 
        alibi_num_heads = 4,
        # alibi_learned = True
    )
)

model(x = torch.randint(0, 1000, (3, 512)))
model(x = torch.randint(0, 1000, (3, 513)))  # RuntimeError at L282
model(x = torch.randint(0, 1000, (3, 511)))  # RuntimeError at L273
```

### CODE REVIEW

**Comment by lucidrains** [comment]
@ilya16  oh thank you! @jstjohn ^ just so you know!

**Comment by jstjohn** [comment]
Are you sure about the rearrange change? I've been using the code as it was, and at least by eye this looks like it would change shape to be one less...

**Comment by jstjohn** [comment]
The error above happens when x is passed in as 2d?

**Comment by jstjohn** [comment]
Caveats being that I have not used it with different sized inputs.

**Comment by ilya16** [comment]
@jstjohn you can safely omit the first (batch) `bias` dimension as PyTorch will handle unequal number of dimensions in `qk_dots` and `bias` by adding 1-sized dimension on the left internally (https://github.com/lucidrains/x-transformers/pull/84#discussion_r854631355). 

The results are the same for `bias` shapes `(1, h, i, j)` and `(h, i, j)`

**Comment by jstjohn** [comment]
Great, as long as you thought about it!

**Pull request merged**
