### PR TITLE
Fix rotary embeddings when mems != None

### PR DESCRIPTION
**Pull request by pfeatherstone**

### CODE REVIEW

**Comment by pfeatherstone** [comment]
It's now ONNX-exportable too

**Comment by pfeatherstone** [comment]
I haven't checked all use cases. But my use case is fixed. Hopefully, I haven't broken other people's code.

**Comment by pfeatherstone** [comment]
@lucidrains Ready for review

**Comment by lucidrains** [comment]
normally i would be more liberal with accepting PRs, but this one required a bit more strategizing

sorry for ignoring it! A for effort

**Comment by pfeatherstone** [comment]
Cheers. There is still the issue with where the mems are recorded when return_mems==True.
When using pre-layer normalisation, it's an issue

**Comment by lucidrains** [comment]
@pfeatherstone oh yea! want to open a PR for that one

that one is more likely an instant accept

**Comment by pfeatherstone** [comment]
Will do this weekend.

**Comment by lucidrains** [comment]
actually, that is tricky too

i'll just take care of it

**Comment by lucidrains** [comment]
@pfeatherstone ok its taken care of https://github.com/lucidrains/x-transformers/commit/49b196e8a9da707c9bf16a59f9d09ed6200dc0e7

**Comment by pfeatherstone** [comment]
Cheers. The way I did it was to record mems inside the Attention layer. Basically directly before prepending old mems I save new mems.

**Comment by lucidrains** [comment]
@pfeatherstone yea i thought you did it that way, which is why i just went ahead and did it. thanks for uncovering the issue anyhow!

**Pull request closed without merging**
