### PR TITLE
Slight modifications to alibi which allow for bidirectional position embedding

### PR DESCRIPTION
**Pull request by jstjohn**
## Changes to AlibiPositionalBias
Alibi weights before change were only appropriate if an upper triangular mask is applied on the qk dot product:
image

Alibi weights after change are now appropriate for bidirectional attention without a mask, and should be equivalent with a mask:
image

## Changes to LearnedAlibiPositionalBias
Alibi weights before change were not maximal on the diagonal if the full attention matrix in unmasked form was presented, so they were only usable with an upper triangular mask:
image
After the change Alibi weights in the learned module match the base module

### CODE REVIEW

**Comment by lucidrains** [comment]
@jstjohn ohh yea, this makes sense, but i do account for it https://github.com/lucidrains/x-transformers/blob/main/x_transformers/x_transformers.py#L797 already

the main reason i kept the base Alibi the way it is, is because Ofir's original code was like that

**Comment by jstjohn** [comment]
There is another issue though that I didn’t call out. The bidirectional=True version has the opposite pattern you would want. The upper and lower corner has the max rather than the max being along the diagonal. So this also fixes that issue.

**Comment by jstjohn** [comment]
But then again since bidirectional and non bidirectional should be equivalent when implemented and masked, it seems easiest to drop that option and just implement it in the general way?

**Comment by lucidrains** [comment]
@jstjohn yes that is true, lets go for your way, thank you for the PR!

**Pull request merged**
